# Welcome to Jekyll!
#

# Site settings
title: Escuela Artistica Balles
description: |
 Bienvinid@ a la página web de la Escuela Artistica Balles.
 
 Recuerda que miles de cosas se expresan con tan solo un movimiento.
owner: Valeria Ballesteros Rodriguez # or company name
first_published: 2022 # if migrating another site, the year of your first publish
email: valbalror@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<ValBal>
  github: https://github.com/<ValBalle>
  facebook-official: https://facebook.com/<ValBal>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
