# Welcome to Jekyll!
#

# Site settings
title: Escuela Artistica Balles
description: |
 Bienvenid@ a la página web de la Escuela Artistica Balles.
 
 Recuerda que miles de cosas se expresan con tan solo un movimiento.
owner: Valeria Ballesteros Rodriguez # or company name
first_published: 2022 # if migrating another site, the year of your first publish
email: valbalror@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<ValBal>
  github: https://escuela-artistica-balles.github.io/
  facebook-official: https://facebook.com/<ValBal>
  instagram:
  
# Build settings
markdown: kramdown
#sass:
#  style: compressed
